name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
      greeting:
        description: 'Type of greeting'
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Display Greeting
        run: |
          echo "What's happening?  ${{ inputs.greeting }}, ${{ inputs.name }}!!!!"
